substitutions:
  name: "esphome-boilermon"
  friendly_name: "ESPHome - Boiler Mon"
esphome:
  name: ${name}
  includes:
  libraries:
  - "Wire"
esp32:
  board: lolin32
#esp8266:
#  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-3Cacc3"
    password: "6MQMnzzB3lpp"

captive_portal:

boilermon:
  address: 0x38
  sda: SDA
  scl: SCL
  
# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 60s

  - platform: boilermon
    boiler_status:
      name: ${name} Status
    boiler_value:
      name: ${name} Temperature
      unit_of_measurement: "°F"


status_led:
  pin: GPIO5


switch:
- platform: gpio
  pin: GPIO19
  id: MODE_BTN
  name: "Mode Button"
  on_turn_on:
  - delay: 250ms
  - switch.turn_off: MODE_BTN 
- platform: gpio
  pin: GPIO23
  id: STEP_BTN
  name: "Step Button"
  on_turn_on:
  - delay: 250ms
  - switch.turn_off: STEP_BTN

